export enum RealtyOfferPublishStatus {
  ACTIVE = 1,
  REMOVED = 3,
  CANCELED = 4,
  ACCEPTED = 14,
  INSIGNATURE = 27,
  SIGNED = 28,
  DEAD = 29,
  CHARGEEMITED = 30,
  PAID = 31,
  WAITINGFORCHARGE = 32,
  WAITINGFORFINANCIAL = 33,
  CANCELLATION = 34, //distract
  WAITINGFORCOMMERCIAL = 35
}
